behaviors:
  TauAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.00003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 12
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      memory:
        memory_size: 256
        sequence_length: 256
        num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.995
        strength: 0.1
        network_settings:
          normalize: true
          hidden_units: 256
          num_layers: 4
          learning_rate: 0.00003
    keep_checkpoints: 100
    checkpoint_interval: 250000
    threaded: true
    max_steps: 25000000
    time_horizon: 256
    summary_freq: 10000
