behaviors:
  TauAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 4096
      learning_rate: 0.00003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.995
        strength: 0.1
        network_settings:
          normalize: true
          hidden_units: 256
          num_layers: 4
          learning_rate: 0.00003
    keep_checkpoints: 10
    checkpoint_interval: 100000
    threaded: true
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 10000
