behaviors:
  TauAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: linear
      batch_size: 256
      buffer_size: 100000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 30.0
      save_replay_buffer: false
      init_entcoef: 0.01
      reward_signal_steps_per_update: 30.0
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 16
      vis_encode_type: simple
      memory:
        sequence_length: 256
        memory_size: 1024
        num_layers: 8
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 1024
          num_layers: 16
      curiosity:
        gamma: 0.995
        strength: 0.1
        network_settings:
          normalize: true
          hidden_units: 1024
          num_layers: 16
          learning_rate: 0.0003
    keep_checkpoints: 10
    checkpoint_interval: 100000
    threaded: true
    max_steps: 1000000
    time_horizon: 256
    summary_freq: 10000
