behaviors:
  TauAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: linear
      batch_size: 1000
      buffer_size: 100000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 30.0
      save_replay_buffer: false
      init_entcoef: 0.01
      reward_signal_steps_per_update: 30.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 5
      vis_encode_type: simple
      memory:
        sequence_length: 1000
        memory_size: 128
        num_layers: 5
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 5
      curiosity:
        gamma: 0.995
        strength: 0.1
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 5
          learning_rate: 0.0003
    keep_checkpoints: 1
    checkpoint_interval: 100000 
    threaded: true
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 10000
